### ISSUE TITLE
读取速度太慢了。

### ISSUE THREAD

**Issue by smirkingbl** [ziqin/ArdComLib#2]
Arduino似乎无法一次接收太长的字符串，所以以下数据请求（亦即目前项目中的所有传感器的列表）发送到设备上后，返回的状态码是1。

`{watchers:["Temperature", "Sunlight", "Gases", "Flame", "Human", "Dht11_Humidity"]}`

于是我们目前只好把所有传感器的名称分成两部分，分别向Arduino发送，结果就是读取时间高于500ms，再加上网络延迟，基本没办法在网页前端实时显示当下的数据。

**Comment by ziqin** [comment]
@refexchange 

### 关于延迟

读取时间高于 500ms 一般漏了 `\n` 造成的。如果是用 Arduino IDE 的串口调试器进行调试，请将行末结束符设置为换行符(LF)，应该就能获得接近实时的响应速度了。

---

### 关于长度限制

ArdComLib 接收的字符串长度确实有一定的限制。由于 Arduino 内存空间有限，过大会导致整个程序挂掉。目前设置的大小是在代码中写死的，在 `Messenger.cpp` 文件中：

``` cpp
void Messenger::work() {
    WatchersDic watchers(watchersList);
    delete watchersList;
    watchersList = NULL;

    for (;;) {
        int status = 0;
        StaticJsonBuffer<200> resBuffer;
        JsonObject& res = resBuffer.createObject();

        String reqStr = Serial.readStringUntil('\n');
        if (reqStr.length() > 0) {
            StaticJsonBuffer<100> reqBuffer;
            JsonObject& req = reqBuffer.parseObject(reqStr);
```

上面代码中的 `StaticJsonBuffer<200> resBuffer` 是响应数据的暂存区，`StaticJsonBuffer<100> reqBuffer` 是请求数据的暂存区。如果解决了前面所述的延迟问题后，仍受长度限制的影响，可以考虑把 `StaticJsonBuffer<100> reqBuffer` 中的 `100` 稍微改大一点。

如果实在不行，还可以考虑把 Watcher 的名称改短一点，例如：Temperature 改成 Tmp，Sunlight 改成 lt……
